### ISSUE TITLE
Difficulties encountered in running the code

### ISSUE THREAD

**Issue by GuanchengWan** [tengxiao1/GraphACL#1]
Hello,

Thank you for your insightful work and for sharing the code.

While reproducing your code with dataset crocodile, I observed that the backpropagation is exceptionally long, resulting in unacceptably slow training. This is also true in the case of datasets for other heterophilic graphs.

I believe the method itself is not an issue. However, I'm having trouble training it. 

Could you provide any suggestions that might help resolve this problem?

Looking forward to your reply :)

**Comment by tengxiao1** [comment]
Hi,

Thank you for your interest. Conducting contrastive training on the crocodile dataset may take several hours, depending on the GPU you use. This is because we manually sample new negative samples for every batch. You can reduce the training time by decreasing the frequency of sampling negative samples.
